# -*- coding: utf-8 -*-
"""pg

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193NodTOGjbPer0KqNkW4jkHjgbo7UD0F

# Model Trainer

## Data Preprocess:
- clean
- split
- get_features
- normalise
---

## First round of training:

> train if_model with benign_data → predict **all data** → feed to surrogate → get imp scores

> train rf_model with x_train → predict x_test → get imp scores

> get top n combined features
---

## Second round of training:

> train if_model with benign_data with selected features → predict **all data** → get [anomaly scores]

> train kmeans with benign_data with normalised **all data** → transform **all data** → get [kmeans distances]

> attach [anoamly scores] & [kmeans distances] to **all data**

> split new **all data**

> train rf_model with x_train → predict x_test

---

## Evaluate model performance
> get classification report & metric

# Performance with scores & distances compare to rf only prediction
> train if and kmeans to get scores & distances → train rf with dataset attached with scores & distances

> train rf only

# Load data
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
from joblib import dump, load

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix,ConfusionMatrixDisplay, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

FILEPATH = "traffic_data/training_data/"

files = [
    "Friday1-Botnet.csv",
    # "Friday2-PortScan.csv",
    "Friday3-DDos.csv",
    # "Monday-Benign.csv",
    # "Thursday1-WebAttacks.csv",
    # "Thursday2-Infilteration.csv",
    # "Tuesday-BruteForce.csv",
    "Wednesday-DDos.csv",
]
# test_files2 = [
#     "Thursday2-Infilteration.csv",
#     "Wednesday-DDos.csv",
# ]
test_files = [f"{FILEPATH}{file}" for file in files]

# Read and combine all CSVs
raw = pd.concat([pd.read_csv(file) for file in test_files], ignore_index=True)
# raw.to_csv("raw_test.csv", index=False)
# print('raw exported.')
# test_raw= pd.concat([pd.read_csv(file) for file in test_files2], ignore_index=True)

"""# Data Cleaning"""

def clean_data(df):
    # tidy
    df.columns = df.columns.str.strip()
    df['Label'] = df['Label'].apply(lambda x: 0 if x == 'BENIGN' else 1).astype(int)
    df = df.drop(columns='Fwd Header Length.1') # duplicate column

    # clean
    df.drop_duplicates(inplace=True)

    # get features, prepare for interpolate()
    features = df.drop(columns= 'Label')
    labels = df['Label']

    # check missing values
    missing = features.isna().sum()
    print(missing.loc[missing > 0])

    # replace
    features.replace([np.inf, -np.inf], np.nan, inplace = True)

    categorical_columns = features.select_dtypes(include=['object']).columns
    print("Categorical columns:", categorical_columns)

    # handle
    features.interpolate(inplace=True)

    # Reattach labels for getting benign rows
    df = features.copy()
    df['Label'] = labels
    benign_data = df[df['Label'] == 0].drop(columns=['Label'])
    features = df.drop(columns= 'Label') # update features

    return features, labels, benign_data

df=raw.copy()
all_features, target_labels, benign_data = clean_data(df)

# test_df = test_raw.copy()
# test_features, test_labels, test_benign_data = clean_data(test_df)

"""## Check contamination rate"""

# Check unique ratio
unique, counts = np.unique(target_labels, return_counts=True)
print(dict(zip(unique, counts)))
print(target_labels)

# Check anomaly% for total data
total = len(target_labels)
benign_count = len(benign_data)
anomaly_count = total - benign_count
print(f'Total anomaly rows in dataframe: {anomaly_count}/{total}')
print(f'Contamination rate in dataframe: {anomaly_count/total *100 :.2f}%')

"""# Train KMeans on Benign Data"""

# drop
kmeans_drop_cols = [
    'Destination Port',
    'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags',
    'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count',
    'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count',
]
kmeans_benign_features = benign_data.drop(columns=kmeans_drop_cols)

# Normalisation
scaler = StandardScaler()
kmeans_benign_data = scaler.fit_transform(kmeans_benign_features)
kmeans_features = scaler.fit_transform(all_features.drop(columns=kmeans_drop_cols))

# Fit KMeans
kmeans = KMeans(n_clusters=10, random_state=42)
kmeans.fit(kmeans_benign_features)

# get distance for all data
distances = kmeans.transform(kmeans_features)

# get distance for test data
# test_distances = kmeans.transform(test_features.drop(columns=kmeans_drop_cols))


"""# Train Isolation Forest on Benign Data

## Model specific preprocessing
"""

if_prep_data = all_features.copy()

# if_prep_test_data = test_features.copy()

"""## Train model"""

# Initial model
if_model = IsolationForest(n_estimators=300)

# Train with benign data
if_model.fit(benign_data)

"""### Get prediction data & scores for training"""

# Predict all data, prepare for surrogate function
if_raw_pred = if_model.predict(if_prep_data)
if_pred = pd.Series(if_raw_pred).replace({1: 0, -1: 1})

# Prepare for Random Forest: attach anomaly scores & kmeans_distance onto training data (keep)
if_prep_data['anomaly_scores'] = -if_model.decision_function(if_prep_data)
if_prep_data['kmeans_distance'] = distances.min(axis=1)

"""### Get scores for testing"""

# Predict test data
# if_pred = if_model.predict(if_prep_test_data)

# Prepare for Random Forest: attach anomaly scores & kmeans_distance onto test data
# if_prep_test_data['anomaly_scores'] = -if_model.decision_function(if_prep_test_data)
# if_prep_test_data['kmeans_distance'] = test_distances.min(axis=1)

"""### Accuracy"""

# print(accuracy_score(target_labels, if_pred))
# print(classification_report(target_labels, if_pred, digits=4))
# if_model trained with all_features

"""# Random Forest"""

print(if_prep_data.shape)
# print(if_prep_test_data.shape)

"""## Model specific preprocessing"""

x_train, x_test, y_train, y_test = train_test_split(all_features, target_labels, test_size=0.3, shuffle=True)

"""## Train model"""

rf_model = RandomForestClassifier(n_estimators=300, class_weight='balanced')

start_time = time.time()

rf_model.fit(x_train, y_train)

end_time = time.time()
elapsed_time = end_time - start_time
print("\n---------------------")
print(f"Training time for Random Forest with all features: {elapsed_time:.4f} seconds")

# from imblearn.over_sampling import SMOTE

# smote = SMOTE(random_state=42)
# x_train_bal, y_train_bal = smote.fit_resample(x_train, y_train)

# rf_model.fit(x_train_bal, y_train_bal)
# print(classification_report(y_test, rf_model.predict(x_test)))
start_time = time.time()

rf_test_pred = rf_model.predict(x_test)

end_time = time.time()
elapsed_time = end_time - start_time
print(f"Prediction time for Random Forest with all features: {elapsed_time:.4f} seconds")

# print(classification_report(y_test, rf_test_pred, digits=4))
print("\n---------------------")
print(f"Accuracy for Random Forest with all features: {accuracy_score(y_test, rf_test_pred):.4f}")
print(f"Precision for Random Forest with all features: {precision_score(y_test, rf_test_pred):.4f}")
print(f"Recall for Random Forest with all features: {recall_score(y_test, rf_test_pred):.4f}")
print(f"F1 Score for Random Forest with all features: {f1_score(y_test, rf_test_pred):.4f}")
print(f"Confusion Matrix for Random Forest with all features: {confusion_matrix(y_test, rf_test_pred)}")
# print(f"ROC AUC for Random Forest with all features: {roc_auc_score(y_test, rf_test_pred):.4f}")
print("---------------------\n")

"""### Test with unseen data"""

# rf_test_pred_unseen = rf_model.predict(if_prep_test_data)
# print(classification_report(test_labels, rf_test_pred_unseen, digits=2))
# print(accuracy_score(test_labels, rf_test_pred_unseen))

"""# Feature Selection

## Surrogate model (for if_model)
"""

# First round only
sur_model = RandomForestClassifier()
sur_model.fit(all_features, if_pred)

"""## Compare Top features"""

feature_names = all_features.columns
rf_importances = rf_model.feature_importances_
if_importances = sur_model.feature_importances_

print(feature_names.shape)
print(rf_importances.shape)
print(if_importances.shape)

def get_ranked_features(model_name, feature_names, feature_importances_):
    importance_col = f"{model_name}_importance"

    feature_imp_df = pd.DataFrame({
            'feature': feature_names,
        importance_col: feature_importances_
    })

    feature_imp_df = feature_imp_df.sort_values(by=importance_col, ascending=False).reset_index(drop=True)
    return feature_imp_df.set_index('feature')
if_ranked_features = get_ranked_features("if", feature_names, if_importances)
rf_ranked_features = get_ranked_features("rf", feature_names, rf_importances)


"""## Select Features"""

thresholds = [0.01, 0.02, 0.05]

rf_selected_features = {}
if_selected_features = {}

for t in thresholds:
    if_selected_features[t] = if_ranked_features[if_ranked_features['if_importance'] >= t].index.tolist()
    rf_selected_features[t] = rf_ranked_features[rf_ranked_features['rf_importance'] >= t].index.tolist()

def combine_features_list(set1: list, set2: list):
    return list(set(set1) | set(set2))
combined_features_01 = combine_features_list(if_selected_features[0.01], rf_selected_features[0.01])
combined_features_02 = combine_features_list(if_selected_features[0.02], rf_selected_features[0.02])
combined_features_05 = combine_features_list(if_selected_features[0.05], rf_selected_features[0.05])

"""### Visulisation of different threshold values"""

def plot_combined_feature_importances(if_selected_features, rf_selected_features, thresholds=[0.01, 0.02, 0.05]):
    for t in thresholds:
        if_df = if_ranked_features[if_ranked_features['if_importance'] >= t]
        rf_df = rf_ranked_features[rf_ranked_features['rf_importance'] >= t] # get dataframe instead of list

        # Merge by feature names
        merged = if_df.join(rf_df, how='outer').fillna(0)

        # Combined importance
        merged['Combined'] = merged['if_importance'] + merged['rf_importance']

        # Sort by combined
        top_features = merged.sort_values('Combined', ascending=False)

        # Plot
        ax = top_features[['if_importance', 'rf_importance']].plot.barh(
            figsize=(10, 8),
            width=0.7,
        )

        plt.title(f"Top Features of IF & RF @ threshold {t} (total: {len(top_features)})")
        plt.xlabel("Importance Score")
        plt.ylabel("Feature")
        plt.gca().invert_yaxis()
        plt.legend(loc='lower right')
        plt.tight_layout()
        plt.show()
        plt.savefig(f"Top Features of IF & RF threshold {t} (total {len(top_features)}).png", bbox_inches='tight')
plot_combined_feature_importances(if_selected_features, rf_selected_features)

"""# Second Round"""

def train_and_predict_if(benign, data): # benign  & all data
    if_model = IsolationForest(n_estimators=300)
    if_model.fit(benign)

    preds = pd.DataFrame(columns=['if_anomaly_score', 'if_raw_pred', 'if_pred'])
    preds['if_raw_pred'] = if_model.predict(data)
    preds['if_pred'] = preds['if_raw_pred'].replace({1: 0, -1: 1})  # returns 1 (normal), -1 (anomaly)
    preds['if_anomaly_score'] = -if_model.decision_function(data)
    return if_model, preds

def train_and_transform_kmeans(benign, data): # benign & all data
    kmeans = KMeans(n_clusters=10)
    kmeans.fit(data)
    distances = kmeans.transform(data)
    return kmeans, distances.min(axis=1)

def train_and_predict_rf(x_train, x_test, y_train, y_test,t=None):
    rf_model = RandomForestClassifier(n_estimators=300)
    
    train_start_time = time.time()
    rf_model.fit(x_train, y_train)
    train_end_time = time.time()
    train_elapsed_time = train_end_time - train_start_time
    
    pred_start_time = time.time()
    preds =  rf_model.predict(x_test)
    pred_end_time = time.time()
    pred_elapsed_time = pred_end_time - pred_start_time
    print("\n---------------------")
    print(f"Training time for RF model with {t} threshold selected features: {train_elapsed_time:.4f} seconds")
    print(f"Prediction time for RF model with {t} threshold selected features: {pred_elapsed_time:.4f} seconds\n")
    # print(f"Classification Report for Random Forest with {t} threshold selected features: {classification_report(y_test, preds, digits=4)}")
    print(f"Accuracy for RF model with {t} threshold selected features: {accuracy_score(y_test, preds):.4f}")
    print(f"Precision for RF model with {t} threshold selected features: {precision_score(y_test, preds):.4f}")
    print(f"Recall for RF model with {t} threshold selected features: {recall_score(y_test, preds):.4f}")
    print(f"F1 Score for RF model with {t} threshold selected features: {f1_score(y_test, preds):.4f}")
    print(f"Confusion Matrix for RF model with {t} threshold selected features: {confusion_matrix(y_test, preds)}")
    print("---------------------\n")
    return rf_model, preds

# create new df with selected features
features_01_df = all_features[[col for col in combined_features_01 if col in all_features.columns]]
features_02_df = all_features[[col for col in combined_features_02 if col in all_features.columns]]
features_05_df = all_features[[col for col in combined_features_05 if col in all_features.columns]]
print(features_01_df.columns)
"""#### if_model"""

features_01_benign_data = benign_data[[col for col in combined_features_01 if col in benign_data.columns]]
features_02_benign_data = benign_data[[col for col in combined_features_02 if col in benign_data.columns]]
features_05_benign_data = benign_data[[col for col in combined_features_05 if col in benign_data.columns]]

# Train Isolation Forest
if_model_01, if_preds_01 = train_and_predict_if(features_01_benign_data, features_01_df)
if_model_02, if_preds_02 = train_and_predict_if(features_02_benign_data, features_02_df)
if_model_05, if_preds_05 = train_and_predict_if(features_05_benign_data, features_05_df)

"""#### kmeans_model"""

k2_drop_cols = ['Destination Port',  ]

k_01_df = scaler.fit_transform(features_01_df.drop(columns=k2_drop_cols))
k_02_df = scaler.fit_transform(features_02_df.drop(columns=k2_drop_cols))
k_05_df = scaler.fit_transform(features_05_df)

k_begnin_01= scaler.fit_transform(features_01_benign_data.drop(columns=k2_drop_cols))
k_begnin_02= scaler.fit_transform(features_02_benign_data.drop(columns=k2_drop_cols))
k_begnin_05= scaler.fit_transform(features_05_benign_data)

k_model_01, kmeans_distances_01 = train_and_transform_kmeans(k_begnin_01, k_01_df)
k_model_02, kmeans_distances_02 = train_and_transform_kmeans(k_begnin_02, k_02_df)
k_model_05, kmeans_distances_05 = train_and_transform_kmeans(k_begnin_05, k_05_df)



"""#### attach new scores & distances"""

def add_additional_features(data_subset, anomaly_scores, kmeans_distances):
    # Add anomaly scores and KMeans distances as new columns
    data_subset['anomaly_scores'] = anomaly_scores
    data_subset['kmeans_distances'] = kmeans_distances
    return data_subset

# For each threshold, prepare the data by adding anomaly scores and KMeans distances (dont need to recompute the unsuperverised values)
features_01_df = add_additional_features(features_01_df, if_preds_01['if_anomaly_score'], kmeans_distances_01)
features_02_df = add_additional_features(features_02_df, if_preds_02['if_anomaly_score'], kmeans_distances_02)
features_05_df = add_additional_features(features_05_df, if_preds_05['if_anomaly_score'], kmeans_distances_05)

print(features_01_df.columns)

"""#### rf_model"""

# train test split for rf_model
x_train_01, x_test_01, y_train_01, y_test_01 = train_test_split(features_01_df, target_labels, test_size=0.3, shuffle=True)
x_train_02, x_test_02, y_train_02, y_test_02 = train_test_split(features_02_df, target_labels, test_size=0.3, shuffle=True)
x_train_05, x_test_05, y_train_05, y_test_05 = train_test_split(features_05_df, target_labels, test_size=0.3, shuffle=True)

# Train Random Forest
rf_model_01, rf_test_pred_01 = train_and_predict_rf(x_train_01, x_test_01, y_train_01,y_test_01,t=0.01)
rf_model_02, rf_test_pred_02 = train_and_predict_rf(x_train_02, x_test_02, y_train_02,y_test_02, t=0.02)
rf_model_05, rf_test_pred_05 = train_and_predict_rf(x_train_05, x_test_05, y_train_05,y_test_05, t=0.05)


"""# Model performances"""

def compare_if_model_precision(
    model_name,
    true_labels,
    predictions_dict
):
    pred_labels_dict = list(predictions_dict.keys())
    accuracies = [
        precision_score(true_labels, predictions_dict[label]) for label in pred_labels_dict
    ]

    x = np.arange(len(pred_labels_dict))
    width = 0.6

    plt.figure(figsize=(10, 6))
    bars = plt.bar(x, accuracies)

    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width() / 2, height + 0.01,
                 f'{height:.4f}', ha='center', va='bottom')

    plt.xticks(ticks=x, labels=pred_labels_dict, rotation=15)
    plt.ylim(0, 1.05)
    plt.ylabel("Precision")
    plt.title(f"Precision Comparison of {model_name} Models\n(with different feature sets)")
    plt.tight_layout()
    plt.show()
    plt.savefig(f"Precision Comparison of {model_name} Models (with different feature sets).png", bbox_inches='tight')

if_accuracies = compare_if_model_precision(
    model_name="Isolation Forest",
    true_labels=target_labels,
    predictions_dict={
        'All features': if_pred,
        '.01 threshold features': if_preds_01['if_pred'],
        '.02 threshold features': if_preds_02['if_pred'],
        '.05 threshold features': if_preds_05['if_pred'],
    }
)

def compare_rf_model_precision(
    model_name,
    true_labels_dict,
    predictions_dict
):
    pred_labels = list(predictions_dict.keys())
    accuracies = []

    for label in pred_labels:
        # Use the corresponding true_labels for each prediction
        true_labels = true_labels_dict[label]
        pred = predictions_dict[label]
        acc = precision_score(true_labels, pred)
        accuracies.append(acc)

    x = np.arange(len(pred_labels))
    width = 0.6

    plt.figure(figsize=(10, 6))
    bars = plt.bar(x, accuracies)

    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width() / 2, height + 0.01,
                 f'{height:.4f}', ha='center', va='bottom')

    plt.xticks(ticks=x, labels=pred_labels, rotation=15)
    plt.ylim(0, 1.05)
    plt.ylabel("Precision")
    plt.title(f"Precision Comparison of {model_name} Models\n(with different feature sets)")
    plt.tight_layout()
    plt.show()
    plt.savefig(f"Precision Comparison of {model_name} Models (with different feature sets).png", bbox_inches='tight')

rf_accuracies = compare_rf_model_precision(
    model_name="Random Forest",
    true_labels_dict={
        "All features": y_test,
        ".01 threshold features": y_test_01,
        ".02 threshold features": y_test_02,
        ".05 threshold features": y_test_05,
    },
    predictions_dict={
        'All features': rf_test_pred,
        '.01 threshold features': rf_test_pred_01,
        '.02 threshold features': rf_test_pred_02,
        '.05 threshold features': rf_test_pred_05,
    }
)


# def get_confusion_matrix(y_true, y_pred, tag=""):
#     cm = confusion_matrix(y_true, y_pred)
#     disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=[0,1])
#     disp.plot()
#     disp.savefig(f"Confusion Matrix of Random Forest with {tag} features.png", bbox_inches='tight')

# original_cm = confusion_matrix(y_test, rf_test_pred,"all")
# cm_01 = get_confusion_matrix(y_test_01, rf_test_pred_01, "t = .01")
# cm_02 = get_confusion_matrix(y_test_02, rf_test_pred_02, "t = .02")
# cm_05 = get_confusion_matrix(y_test_05, rf_test_pred_05, "t = .05")

"""# Save models"""
dump(if_model_01, "trained_models/if_model_01.joblib")
dump(k_model_01, "trained_models/kmeans_model_01.joblib")
dump(rf_model_01, "trained_models/rf_model_01.joblib")




importances = rf_model_01.feature_importances_
sorted_indices = np.argsort(importances)[::-1]
sorted_features = np.array(feature_names)[sorted_indices]

plt.figure(figsize=(12, 6))

# Plot all points first
plt.plot(importances[sorted_indices], marker='o', linestyle='-', label='Other features')

# Now highlight anomaly_scores and kmeans_distance separately
for idx, feature in enumerate(sorted_features):
    if feature == 'anomaly_scores':
        plt.plot(idx, importances[sorted_indices][idx], marker='s', color='red', markersize=10, label='anomaly_scores')
    elif feature == 'kmeans_distance':
        plt.plot(idx, importances[sorted_indices][idx], marker='^', color='green', markersize=10, label='kmeans_distance')

thresholds = 0.01, .02,.05
for t in thresholds:
    plt.axhline(y=t, linestyle='--', label=f'threshold = {t}')

plt.title('Feature Importance Scores for rf_model')
plt.xlabel('Features sorted by importance')
plt.ylabel('Importance Score')
plt.grid()

# To avoid duplicate labels if multiple points (safe way)
handles, target_labels = plt.gca().get_legend_handles_labels()
by_label = dict(zip(target_labels, handles))
plt.legend(by_label.values(), by_label.keys())
plt.savefig("Feature Importance Scores for rf_model.png", bbox_inches='tight')
plt.show()


# # Metrics
# accuracy = [0.98, 0.978]
# precision = [0.97, 0.975]
# recall = [0.96, 0.95]
# f1_score = [0.965, 0.9625]

# # X-axis positions
# x = np.arange(len(models))

# # Width of each bar
# width = 0.2

# # Create figure and axes
# fig, ax = plt.subplots(figsize=(10, 6))

# # Plot each metric
# ax.bar(x - width*1.5, accuracy, width, label='Accuracy')
# ax.bar(x - width/2, precision, width, label='Precision')
# ax.bar(x + width/2, recall, width, label='Recall')
# ax.bar(x + width*1.5, f1_score, width, label='F1 Score')

# # Labels and title
# ax.set_ylabel('Scores')
# ax.set_xlabel('Models')
# ax.set_title('Model Performance Comparison')
# ax.set_xticks(x)
# ax.set_xticklabels(models)
# ax.set_ylim(0.9, 1.0)
# ax.legend()

# # Grid and tight layout
# ax.grid(True, linestyle='--', alpha=0.7)
# plt.tight_layout()

# # Show the plot
# plt.show()